services:
  server1:
    build: ./server
    container_name: server1
    ports:
      - "8091:8091"
    environment:
      - PORT=8091
    volumes:
      - ./dados/server1/blockchain.json:/app/blockchain.json

  server2:
    build: ./server
    container_name: server2
    ports:
      - "8092:8092"
    environment:
      - PORT=8092
    volumes:
      - ./dados/server2/blockchain.json:/app/blockchain.json

  server3:
    build: ./server
    container_name: server3
    ports:
      - "8093:8093"
    environment:
      - PORT=8093
    volumes:
      - ./dados/server3/blockchain.json:/app/blockchain.json
    
  client:
    build: ./client
    container_name: client
    volumes:
      - ./dados/companies.json:/app/companies.json
      - ./dados/points.json:/app/points.json
