services:
  client1:
    build: ./client
    container_name: client1
    ports:
      - "8091:8091"
    environment:
      - PORT=8091
    volumes:
      - ./dados/blockchain.json:/app/blockchain.json
      - ./dados/points.json:/app/points.json

  client2:
    build: ./client
    container_name: client2
    ports:
      - "8092:8092"
    environment:
      - PORT=8092
    volumes:
      - ./dados/blockchain.json:/app/blockchain.json
      - ./dados/points.json:/app/points.json

  client3:
    build: ./client
    container_name: client3
    ports:
      - "8093:8093"
    environment:
      - PORT=8093
    volumes:
      - ./dados/blockchain.json:/app/blockchain.json
      - ./dados/points.json:/app/points.json
